on: [pull_request]

name: Lint and Build

jobs:
  # 一回剥がしたのでやめとく
  # あとで直す
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v6
  #   - run: npm ci
  #   - run: npm run lint
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
    - run: npm ci
    - run: npm run build
